---
- name: Restart journald
  ansible.builtin.systemd:
    name: "systemd-journald"
    state: restarted
- name: Restart logind
  ansible.builtin.systemd:
    name: "systemd-logind"
    state: restarted
- name: Restart ssh
  ansible.builtin.systemd:
    name: "ssh"
    state: restarted
- name: Restart ntp
  ansible.builtin.systemd:
    name: ntp
    state: restarted
- name: Restart locale
  ansible.builtin.command: locale-gen
