---
- name: Block checks ansible_host
  block:
    - name: Hosts
      ansible.builtin.debug: msg="{{ item }}"
    - name: Debug
      ansible.builtin.debug: msg="{{ hostvars[item].add_name }}"
      when: hostvar[item].add_name is defined
    - name: 
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }} {{ item }}.{{ domain_project }}.*'
        line: "{{ hostvars[item].ansible_host }} {{ item }} {{ item }}.{{ domain_project }} {{ hostvars[item].add_name | join(' ') }}"
        state: present
      when: 
        - hostvars[item].add_name is defined
    - name: 
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }} {{ item }}.{{ domain_project }}.*'
        line: "{{ hostvars[item].ansible_host }} {{ item }} {{ item }}.{{ domain_project }}"
        state: present
      when: 
        - hostvars[item].add_name is not defined
  when: 
    - hostvars[item].ansible_host is defined
        